// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSVPv9FdwGfifGqZR5f8La7hIm_aA8Ss',
    appId: '1:1067233694322:web:a706aa9c8cdc209530e8eb',
    messagingSenderId: '1067233694322',
    projectId: 'projekmuseglo',
    authDomain: 'projekmuseglo.firebaseapp.com',
    databaseURL: 'https://projekmuseglo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projekmuseglo.firebasestorage.app',
    measurementId: 'G-RLZ3SEELHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKeIF-8ehcUSbof2_HmnrBQXMKRtwjvKw',
    appId: '1:1067233694322:android:272c16b8f861ee2a30e8eb',
    messagingSenderId: '1067233694322',
    projectId: 'projekmuseglo',
    databaseURL: 'https://projekmuseglo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projekmuseglo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXT4qBmunINLQl33gllbkGMpNjc_rTuBo',
    appId: '1:1067233694322:ios:f1f45fba4dcc04dd30e8eb',
    messagingSenderId: '1067233694322',
    projectId: 'projekmuseglo',
    databaseURL: 'https://projekmuseglo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projekmuseglo.firebasestorage.app',
    iosBundleId: 'com.example.museglo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXT4qBmunINLQl33gllbkGMpNjc_rTuBo',
    appId: '1:1067233694322:ios:f1f45fba4dcc04dd30e8eb',
    messagingSenderId: '1067233694322',
    projectId: 'projekmuseglo',
    databaseURL: 'https://projekmuseglo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projekmuseglo.firebasestorage.app',
    iosBundleId: 'com.example.museglo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQSVPv9FdwGfifGqZR5f8La7hIm_aA8Ss',
    appId: '1:1067233694322:web:2c41ce9fe85964ab30e8eb',
    messagingSenderId: '1067233694322',
    projectId: 'projekmuseglo',
    authDomain: 'projekmuseglo.firebaseapp.com',
    databaseURL: 'https://projekmuseglo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projekmuseglo.firebasestorage.app',
    measurementId: 'G-QFP5N13EEC',
  );
}
